### ISSUE TITLE
Creation of dynamic property UcAddress::$nid is deprecated

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/uc_addresses#5]
@argiepiano 

Error:

> Deprecated function: Creation of dynamic property UcAddress::$nid is deprecated in DatabaseStatementBase->fetchAllAssoc() (line 2314 of /app/httpdocs/core/includes/database/database.inc).

**Comment by argiepiano** [comment]
`UcAddress` is defined in `uc_store`. This is an Ubercart bug, not a `uc_addresses` bug.
